version: '3'
services:
    app:
        depends_on:
            - ganache-cli
        command: bash -c "./wait-for-it.sh mongo:27017 && ./wait-for-it.sh ganache-cli:8545 && npm start"
    ganache-cli:
        container_name: test-blockchain
        image: "trufflesuite/ganache-cli:v6.4.3"
        command: ganache-cli -d
        ports:
            - 8545:8545
            - 8546:8546
